### ISSUE TITLE
"Could not find Fallout 4 in you're steam library"

### ISSUE THREAD

**Issue by tjrissi** [Furglitch/modorganizer2-linux-installer#203] opened 2021-01-28 09:42 UTC
I get a popup saying this when the lutris installer is running "Could not find Fallout 3 in your steam library".  Below is the code that is in the installer window when the error shows.

```
lutris-wrapper: /usr/bin/bash
Running /usr/bin/bash -c # clear envs set by Lutris
export LD_LIBRARY_PATH=""

nexus_game_id=fallout4
runner=proton

if [ ! -f "/home/tanner/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh" ]; then
    "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Could not find gameinfo for '$nexus_game_id', remove Lutris cache and try again"
    exit 1
fi

source "/home/tanner/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh"

if [ -z "$game_appid" ]; then
    echo "ERROR: empty game_appid" >&2
    exit 1
elif [ -z "$game_steam_subdirectory" ]; then
    echo "ERROR: empty steam_subdirectory" >&2
    exit 1
fi

shared="/home/tanner/.local/share/modorganizer2"

case "$runner" in
    proton)
        mo2_tricks="vcrun2019"
        mo2_options=""

        if [ -z "$steam_library" ]; then
            steam_library=$("/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh" $game_appid)
        fi

        if [ ! -d "$steam_library" ]; then
            "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
                "Could not find '$game_steam_subdirectory' in your Steam library"
            exit 1
        fi

        game_prefix="$steam_library/steamapps/compatdata/$game_appid/pfx"
        game_installation="$steam_library/steamapps/common/$game_steam_subdirectory"
        game_tricks="$game_protontricks"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options \"\$@\" $game_appid '/home/tanner/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/tanner/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options $game_appid '/home/tanner/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/tanner/Games/mod-organizer-2/download.sh"
        ;;

    wine)
        mo2_tricks="vcrun2019 dotnet40"
        mo2_options="--proton-wine --winever 5.*"

        "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" warnbox \
            "As of version 5.7, Wine still does not fully support Mod Organizer 2.2.1 and later.\nFor this reason this installer uses the Wine version bundled with Proton 5.0.\nMake sure you have Steam and Proton 5.0 installed on your system"

        game_prefix=$( \
            "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                "Inform the path to your wineprefix" \
        )
        if [ -z "$game_prefix" ]; then
            echo "ERROR: Installation canceled by user" >&2
            exit 1
        fi

        game_tricks="$game_winetricks"

        install_path_candidates=( \
            "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/$game_steam_subdirectory" \
            "$game_prefix/drive_c/GOG Games/$game_steam_subdirectory" \
        )
        if [ -n "$game_gog_subdirectory" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/GOG Games/$game_gog_subdirectory" \
            )
        fi
        if [ "$nexus_game_id" == "fallout3" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 3" \
                "$game_prefix/drive_c/GOG Games/Fallout 3" \
            )
        fi

        for path in "${install_path_candidates[@]}"; do
            echo "Searching for game at '$path'"
            if [ -d "$path" ]; then
                echo "Found game"
                game_installation="$path"
                break
            fi
        done

        if [ -z "$game_installation" ]; then
            game_installation=$( \
                "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                    "Could not automatically find the game.\nPlease inform the path where the game is installed" \
            )
            if [ -z "$game_installation" ]; then
                echo "ERROR: installation canceled by user" >&2
                exit 1
            fi
        fi

        # TODO: uncomment once Wine fixes issues with VC2019
        # winever=$( \
        #     "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" textentry \
        #         "Inform which version of Wine you're using\nLeave as * to use the latest version available on Lutris" \
        #         "*" \
        # )
        # if [ -z "$winever" ]; then
        #     echo "ERROR: Installation canceled by user" >&2
        #     exit 1
        # fi

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options \"\$@\" '/home/tanner/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/tanner/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options '/home/tanner/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/tanner/Games/mod-organizer-2/download.sh"
        ;;
esac

if [ -d "/home/tanner/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender" ]; then
    echo "Installing script extender..."

    output=$( \
        cp -af \
        "/home/tanner/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender/." \
        "$game_installation/" 2>&1 \
    )
    if [ "$?" != "0" ]; then
        "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
            "Error while installing script extender: $output"
        exit 1
    fi
fi

mkdir -p "$game_prefix/drive_c/java"
output=$( \
    cp -af \
    "/home/tanner/.cache/lutris/installer/mod-organizer-2/extracted-openjdk/." \
    "$game_prefix/drive_c/java/" 2>&1 \
)
if [ "$?" != "0" ]; then
    "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing OpenJDK: $output"
    exit 1
fi

WINEPREFIX="$game_prefix" \
"/home/tanner/.local/share/lutris/runtime/winetricks/winetricks" -q $mo2_tricks $game_tricks
if [ "$?" != "0" ]; then
    "/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing winetricks, please run Lutris from a terminal and check the logs"
    exit 1
fi

# workaround to stop installation if command fails
echo "success" > '/home/tanner/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation'
Initial process has started with pid 977864
Game is considered started.
Searching for Steam in '/home/tanner/.local/share/Steam'
Found Steam
Searching for Steam in '/home/tanner/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Steam not found in this install path
Searching for game in library '/home/tanner/.local/share/Steam'
Found game
/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
Searching for game in library '/mnt/007676fb-2ddb-458b-a335-2612417ce8eb/SteamLibrary'
Found game
/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
Searching for game in library '/mnt/32609ae3-c405-4c26-92db-58f17da567d5/SteamLibrary'
ERROR: could not find game with APPID '377160'
/home/tanner/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script
```
"/mnt/007676fb-2ddb-458b-a335-2612417ce8eb/SteamLibrary" is where Fallout 4 is installed. I also tried installing Fallout 4 on my OS drive but i had the same issue.

**Comment by tjrissi** [comment] 2021-01-28 09:50
Fixed it. 
Fix is here [160](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/160)

**Comment by rockerbacon** [comment] 2022-01-09 19:59
Duplicate of #160

**Closed by rockerbacon** 2022-01-09 19:59 UTC
