### ISSUE TITLE
Case Sensitivity issues.

### ISSUE THREAD

**Issue by Continous** [Furglitch/modorganizer2-linux-installer#231] opened 2021-07-14 06:07 UTC
Currently, the installer makes no attempt to turn the Skyrim install, or even the installer own working directory, into a non-case-sensitive folder. This usually does not create any issues, however, mods such as SkyUI are notable exceptions, and as a result some users my find a difficult to debug issue with SkyUI will report a failure to detect/use SKSE while other mods will proceed using SKSE without issue. More important to this is the fact that the /Data/Scripts and /Data/scripts directories are considered distinct and unique. While it may not be an elegant solution, it is probably the best solution to attempt to flag the directory as case insensitive in the installer or install script, both for the mod organizer working directory and for the Skyrim directory. This may only work for some people however, so it may just be a better idea to have a script to take any folders and rename them to their lower case counterparts in hopes that'd solve the problem. I really don't know what the solution would be, but SkyUI throws a fit if there are two script folders.

**Comment by rockerbacon** [comment] 2022-01-05 13:17
Duplicate of #188

**Closed by rockerbacon** 2022-01-05 13:17 UTC
