### ISSUE TITLE
 mod organizer can't find steam (but can find skyrim?)

### ISSUE THREAD

**Issue by what-a-scamp** [Furglitch/modorganizer2-linux-installer#571] opened 2024-01-28 23:58 UTC
I installed mod organizer for skyrim special edition it seemed to be fine but when I went to launch the game on steam I got an error

Error 2 ERROR_FILE_NOT_FOUND: Filenotfound. (0x2)
 . binary: 'Z:\home\sanguine\.local\share\Steam\steamapps\common\Skyrim Special Edition\MO\modorganizer2\ModOrganizer.exe'
 . owner: (file not found)
 . rights: (file not found)
 . arguments: ''
 . cwd: 'Z:\home\sanguine\.local\share\Steam\steamapps\common\Skyrim Special Edition\MO\modorganizer2'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok

I went to the folder mentioned and while MO wasn't there modorganizer2\ModOrganizer.exe was so I put it into a folder called MO to see if that would fix it but when i tried to launch the game it wouldn't load again but with no error message this time. I then tried to launch the mod organizer.exe and that worked but when I tried to launch skyrim se from there I got the error 

can't start steam, registry value at 'HKEY_CURRENT_USER\Software\Valve\Steam\SteamExe' is empty or doesn't exist

So I tried reinstalling mod organizer and noticed this 

INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/sanguine/.local/share/Steam'
INFO: game found in '/home/sanguine/.local/share/Steam'
INFO: steam not found in '/home/sanguine/.var/app/com.valvesoftware.Steam/.local/share/Steam'

when I selected skyrim se, it once again said the installation was successful and once again when i went to launch skyrim se I got the same error message ad before. 

I have no clue where to go from here (sorry if this is an obvious mistake I'm new to all of this)

**Comment by rockerbacon** [comment] 2024-01-30 20:59
Duplicate of #346

**Closed by rockerbacon** 2024-01-30 20:59 UTC
