### ISSUE TITLE
2.6.1 installer installs 2.4.4, won't register nxm links, UI scales improperly, attempting to update breaks game installation [Steam Deck]

### ISSUE THREAD

**Issue by mutag3ne** [Furglitch/modorganizer2-linux-installer#577] opened 2024-02-14 00:59 UTC
![Screenshot_20240213_184526](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/101020620/2bfdcbb7-6d59-4d78-9cf9-4299f138d4d3)

Did I just do something horribly wrong? I followed the instructions exactly. I'm not particularly technical with Linux so I haven't the slightest clue where I could look for solutions in that regard.

I tried several different Proton versions (including every version that I had seen recommended), reinstalled the game and MO2 multiple times, same result every time.

**Comment by rockerbacon** [comment] 2024-02-14 11:56
Duplicate of #543

UI scaling has to be configured with winecfg, MO2 doesn't respect the system settings.

Read through all of the open and closed NXM links issues before opening a new issue with specific information on your setup and the issue you're facing.

**Closed by rockerbacon** 2024-02-14 11:56 UTC

**Comment by rockerbacon** [comment] 2024-02-14 12:00
Just noticed this is on a Steam Deck. Duplicate of #317
