### ISSUE TITLE
launching fnv through mo2 trys to launch mo2 again 

### ISSUE THREAD

**Issue by sylveonsylvia** [Furglitch/modorganizer2-linux-installer#608] opened 2024-04-22 00:48 UTC
![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/78629289/d976f2e3-21b4-4752-9e09-5e34f2eebf69)
everything apparently installed correctly so idk whats up

**Comment by AmbyVis** [comment] 2024-04-22 10:21
Having the same issue, can't change launcher settings through MO2 after installing it, have to edit the ini file to change resolution and graphics settings.

**Comment by rockerbacon** [comment] 2024-04-23 10:29
Duplicate of #387

**Closed by rockerbacon** 2024-04-23 10:29 UTC
